In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 

In [2]:
chi = np.array([[1,0,0,0], [0,0,1,0], [0,1,0,1], 
                [0,1,1,0], [0,0,0,1], [1,0,0,1], 
                [0,0,0,1], [0,1,1,0], [0,0,0,1], [0,1,1,0]])

In [3]:
chi

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 0, 1],
       [0, 1, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 1, 0]])

In [4]:
p = np.array([196, 248, 169, 124, 78, 158, 119, 189, 172, 161])
p

array([196, 248, 169, 124,  78, 158, 119, 189, 172, 161])

In [11]:
p_t = p.reshape(-1,1)
print(chi.shape)
print(p_t.shape)

(10, 4)
(10, 1)


In [12]:
S = np.hstack((chi,p_t))

In [17]:
S

array([[  1,   0,   0,   0, 196],
       [  0,   0,   1,   0, 248],
       [  0,   1,   0,   1, 169],
       [  0,   1,   1,   0, 124],
       [  0,   0,   0,   1,  78],
       [  1,   0,   0,   1, 158],
       [  0,   0,   0,   1, 119],
       [  0,   1,   1,   0, 189],
       [  0,   0,   0,   1, 172],
       [  0,   1,   1,   0, 161]])

In [21]:
print(np.mean(p_t))

161.4
